CREATE TABLE IF NOT EXISTS pokemon (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    nivel INT NOT NULL,
    pokebola VARCHAR(255) NOT NULL
);